# travis-ci.com is currently not used,
# and this file may be outdated.
#
# GitHub Actions are used:
# configured via the files in the directory:
# `.github/workflows/`
git:
  depth: 3

language: python

python:
  - "3.8"
  - "3.9"

before_install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt

install:
  # install the package `tla`
  - python setup.py sdist
  - pip install dist/tla-*.tar.gz

script:
  - cd tests/
  - pytest -v --continue-on-collection-errors .

after_success:
  - coveralls
